chore:  Initial commit
hpcc-systems/hpcc-js-wc pull request #1
Opened 2022-02-15 11:47 UTC by GordonSmith

Includes build, test and documentation scaffolding.

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

2022-02-15 11:51 UTC, GordonSmith commented
@jbrundage @jeclrsg This is the initial scaffolding and doesn't contain any web components (yet)

2022-02-16 15:19 UTC, jeclrsg commented on .vitepress/config.ts
> +        repo: "GordonSmith/hpcc-js-wc",
Wasn't sure if this mattered, but I noticed a couple of places that referenced your fork rather than the hpcc-systems repo

2022-02-16 15:20 UTC, jeclrsg commented on .vitepress/config.ts
> +                link: "https://github.com/GordonSmith/hpcc-js-wc/releases"
This was the other place w/ the GordonSmith repo url

2022-02-16 15:39 UTC, GordonSmith commented on .vitepress/config.ts
> +        repo: "GordonSmith/hpcc-js-wc",
Yes will need to fix!

2022-02-16 15:40 UTC, jeclrsg commented on .vitepress/mdWriter.ts
> +                this.writeLinkTagWithUrlDestination(docLinkTag, context);
Are these `writeLinkTag...` fns some of the kinds of things that you mentioned needed to be implemented? I didn't see the definitions.

2022-02-16 15:41 UTC, jeclrsg approved these changes

2022-02-16 15:46 UTC, GordonSmith commented on .vitepress/mdWriter.ts
> +                this.writeLinkTagWithUrlDestination(docLinkTag, context);
Not those ones (from memory) - I suspect this code won't change much if ever.

2022-02-16 15:52 UTC, jeclrsg requested changes
Changing status for changing the GordonSmith -> hpcc-systems repo urls

2022-02-17 05:57 UTC, merged