feat:  Add web component core package
hpcc-systems/hpcc-js-wc pull request #2
Opened 2022-02-18 06:00 UTC by GordonSmith

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

2022-02-18 22:18 UTC, jeclrsg commented on packages/core/src/css.ts
> +        retVal += templateData[i + 1];
I've not done much with template strings like this, so I don't really follow how this is used. Could this not be out of bounds / undefined?

2022-02-18 22:59 UTC, jeclrsg commented on packages/core/src/message.ts
> +    [what in keyof T]+?: Change<T[what]>;
What is this [...]+?: ...? I wasn't even sure what to search for to try and figure that out 😄

2022-02-18 23:00 UTC, jeclrsg commented on packages/core/src/html.ts
> +        html += strings[i + 1];
Likewise here, as mentioned in the css.ts

2022-02-18 23:02 UTC, jeclrsg requested changes
@GordonSmith no changes, I don't think. Just a couple or three questions. Unless those array index spots should be checked.

2022-02-19 06:55 UTC, GordonSmith commented on packages/core/src/css.ts
> +        retVal += templateData[i + 1];
templateData is an array which is always 1 larger than the args array per the specification.

2022-02-19 06:57 UTC, GordonSmith commented on packages/core/src/html.ts
> +        html += strings[i + 1];
Again this is a normal pattern as the "strings" will always be an array 1 larger than the values.

2022-02-19 07:09 UTC, GordonSmith commented on packages/core/src/message.ts
> +    [what in keyof T]+?: Change<T[what]>;
See "Mapping Modifiers":  https://www.typescriptlang.org/docs/handbook/2/mapped-types.html

2022-02-19 08:10 UTC, merged

2022-02-22 14:16 UTC, jbrundage commented on packages/core/src/svg.ts
> +            this._svg.setAttribute("height", `${this.clientHeight - 5}px`);
What is this -5 for?